# Generated by Django 4.2.7 on 2023-11-25 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ServiciosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='detalle',
            field=models.CharField(default='detalle', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(default='descarga.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(default='titulo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
